# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mw_inicial(object):
    def setupUi(self, Mw_inicial):
        Mw_inicial.setObjectName("Mw_inicial")
        Mw_inicial.resize(420, 331)
        Mw_inicial.setStyleSheet("Background-color:black;\n"
"\n"
"QPushButton::Hover{\n"
"border-color:red;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Mw_inicial)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 421, 331))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bangers")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"Background-color:transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, -20, 101, 81))
        self.label_2.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(-30, 240, 101, 81))
        self.label_5.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(340, -10, 101, 81))
        self.label_6.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(180, -50, 101, 81))
        self.label_7.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(-40, 100, 101, 81))
        self.label_8.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(330, 270, 101, 81))
        self.label_10.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(140, 270, 101, 81))
        self.label_9.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(120, 140, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: transparent;\n"
"border-bottom: 1px solid white;\n"
"border-radius:none;\n"
"color:white;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(350, 140, 101, 81))
        self.label_3.setStyleSheet("Background-image: url(C:/Users/Yuri/PycharmProject/anime/img/akatsuki.png);\n"
"Background-size:10px 20px;\n"
"Background-repeat:no-repeat;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Btn_buscar = QtWidgets.QPushButton(self.frame)
        self.Btn_buscar.setGeometry(QtCore.QRect(160, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bangers")
        font.setPointSize(12)
        self.Btn_buscar.setFont(font)
        self.Btn_buscar.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border: 1px solid white;\n"
"\n"
"")
        self.Btn_buscar.setObjectName("Btn_buscar")
        self.label_5.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.Btn_buscar.raise_()
        Mw_inicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mw_inicial)
        QtCore.QMetaObject.connectSlotsByName(Mw_inicial)

    def retranslateUi(self, Mw_inicial):
        _translate = QtCore.QCoreApplication.translate
        Mw_inicial.setWindowTitle(_translate("Mw_inicial", "Busca_anime"))
        self.label.setText(_translate("Mw_inicial", "Busca anime"))
        self.lineEdit.setPlaceholderText(_translate("Mw_inicial", "Digite o nome do anime"))
        self.Btn_buscar.setText(_translate("Mw_inicial", "Buscar"))
